# Generated by Django 4.1.2 on 2022-11-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_client_image_alter_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='image',
            new_name='avatar',
        ),
    ]
